#!/bin/bash
projections=("albersUsa" "albersUsaTerritories" "conicConformalSpain" "conicConformalPortugal" "mercatorEcuador" "transverseMercatorChile" "conicEquidistantJapan")
topojsons=("./data/us.json" "./data/us_territories.json" "./data/provincias.json" "./data/world-50m.json" "./data/world-50m.json" "./data/chile.json" "./data/japan.json")
fields=("states" "us" "provincias" "countries" "countries" "chile" "japan")

tLen=${#projections[@]}

for (( i=0; i<${tLen}; i++ )) do
    test/render ${projections[$i]} ${topojsons[$i]} ${fields[$i]}\
       && [ "$(compare -metric rmse test/samples/${projections[$i]}.png test/output/${projections[$i]}.png null: 2>&1)" = "0 (0)" ] \
 || echo "✗ test/output/${projections[$i]}.png and test/samples/${projections[$i]}.png differ"
done
