#!/bin/bash
projections=("albersUsa" "conicConformalSpain" "conicConformalPortugal")
topojsons=("./data/us.json" "./data/provincias.json" "./data/world-50m.json")
fields=("states" "provincias" "countries")


tLen=${#projections[@]}

for (( i=0; i<${tLen}; i++ )) do
    test/render ${projections[$i]} ${topojsons[$i]} ${fields[$i]}\
       && [ "$(compare -metric rmse test/samples/${projections[$i]}.png test/output/${projections[$i]}.png null: 2>&1)" = "0 (0)" ] \
 || echo "✗ test/output/${projections[$i]}.png and test/samples/${projections[$i]}.png differ"
done
